server:
  port: 8081

spring:
  application:
    ## 应用名
    name: consum
  ## nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


logging:
  level:
    com.xt.open.jmall.product.remote.feignclients.CartFeignClient: debug